# @name Manual Websocket Event
POST localhost:3000/websocket/3
Content-Type: application/json

{
  "phoneSaleId": 3,
  "paymentStatus": "approved"
}

###
# @name Wiremock test
POST localhost:8080/payment
Content-Type: application/json

{
  "idOrPassport": "123",
  "amountMinor": 5000
}

###
# @name Telco webhook
POST localhost:5173/api/payment/webhook
Content-Type: application/json

{
  "paymentId": "406817d8-2e1c-4399-b97f-fb16d65cc68c",
  "paymentStatus": "approved"
}
