name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Start test containers
        run: |
          cp .env.example .env.local
          tests/docker/start_testcontainers.sh

      - name: Run Playwright tests
        run: pnpm exec playwright test

      # Teardown
      - name: Shutdown test containers
        run: docker compose down
        working-directory: tests/docker
        if: always()
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
